spring.application.name=notification-delivery-sys

spring.datasource.url=jdbc:postgresql://localhost:5432/notifications_db
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.properties.max.block.ms=3000

# Ensures that Kafka Producer doesn't retry messages again and again due to network or broker errors.
# Prevents retry-related duplicates
spring.kafka.producer.properties.max.enable.idempotence=true
spring.kafka.producer.properties.max.retries=2147483647
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.properties.compression.type=snappy

spring.kafka.consumer.group-id=notifications-test-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest

management.endpoints.web.exposure.include=prometheus

